{{- template "common.configmap" (list . "mariadb.configmap") -}}
{{- define "mariadb.configmap" -}}
data:
  my.cnf: |-
{{- if .Values.config }}
{{ .Values.config | indent 4 }}
{{- end -}}
{{- end -}}
