{{- template "common.deployment" (list . "nginx.deployment") -}}
{{- define "nginx.deployment" }}
## Define overrides for your Deployment resource here, e.g.
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "nginx.deployment.container") }}
{{- end -}}
{{- define "nginx.deployment.container" -}}
## Define overrides for your Container here, e.g.
# ports:
# - name: http
#   containerPort: 80
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
{{- end -}}
